# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Checkrun

on:
  pull_request:
    branches: [master]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    # if: ${{ (github.event_name == 'push' && !contains(toJSON(github.event.commits[0].message), '[skip ci]')) || (github.event.issue.pull_request && github.event.comment.body == '/build') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git-config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Echo
        run: |
          cat README.md
          echo ${ github.event_name }
