# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Checkrun

on:
  pull_request_review_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event.comment.body == '/check' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git-config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Echo
        run: |
          cat README.md
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
