# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Snapshot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/snapshot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      - name: git-config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.THUNDRA_GITHUB_ACCESS_TOKEN }}
        run: echo "Snapshot"
